// Lista pública de municipios de Colombia agrupados por departamento.
// Fuente: nomenclatura oficial DANE de divisiones político-administrativas.
// Solo contiene geografía (departamento + municipio) — la asignación a cada
// categoría de despacho y sus precios se configuran en /admin/envios y viven
// en la base de datos (tabla municipios), no aquí.

export type MunicipioSeed = { department: string; name: string };

export const COLOMBIA_MUNICIPIOS: MunicipioSeed[] = [
  { department: "Amazonas", name: "Leticia" },
  { department: "Amazonas", name: "Puerto Nariño" },
  { department: "Antioquia", name: "Abejorral" },
  { department: "Antioquia", name: "Abriaquí" },
  { department: "Antioquia", name: "Alejandría" },
  { department: "Antioquia", name: "Amagá" },
  { department: "Antioquia", name: "Amalfi" },
  { department: "Antioquia", name: "Andes" },
  { department: "Antioquia", name: "Angelópolis" },
  { department: "Antioquia", name: "Angostura" },
  { department: "Antioquia", name: "Anorí" },
  { department: "Antioquia", name: "Anzá" },
  { department: "Antioquia", name: "Apartadó" },
  { department: "Antioquia", name: "Arboletes" },
  { department: "Antioquia", name: "Argelia" },
  { department: "Antioquia", name: "Armenia" },
  { department: "Antioquia", name: "Barbosa" },
  { department: "Antioquia", name: "Bello" },
  { department: "Antioquia", name: "Belmira" },
  { department: "Antioquia", name: "Betania" },
  { department: "Antioquia", name: "Betulia" },
  { department: "Antioquia", name: "Briceño" },
  { department: "Antioquia", name: "Buriticá" },
  { department: "Antioquia", name: "Caicedo" },
  { department: "Antioquia", name: "Caldas" },
  { department: "Antioquia", name: "Campamento" },
  { department: "Antioquia", name: "Caracolí" },
  { department: "Antioquia", name: "Caramanta" },
  { department: "Antioquia", name: "Carepa" },
  { department: "Antioquia", name: "Carolina del Príncipe" },
  { department: "Antioquia", name: "Caucasia" },
  { department: "Antioquia", name: "Cañasgordas" },
  { department: "Antioquia", name: "Chigorodó" },
  { department: "Antioquia", name: "Cisneros" },
  { department: "Antioquia", name: "Ciudad Bolívar" },
  { department: "Antioquia", name: "Cocorná" },
  { department: "Antioquia", name: "Concepción" },
  { department: "Antioquia", name: "Concordia" },
  { department: "Antioquia", name: "Copacabana" },
  { department: "Antioquia", name: "Cáceres" },
  { department: "Antioquia", name: "Dabeiba" },
  { department: "Antioquia", name: "Donmatías" },
  { department: "Antioquia", name: "Ebéjico" },
  { department: "Antioquia", name: "El Bagre" },
  { department: "Antioquia", name: "El Carmen de Viboral" },
  { department: "Antioquia", name: "El Peñol" },
  { department: "Antioquia", name: "El Retiro" },
  { department: "Antioquia", name: "El Santuario" },
  { department: "Antioquia", name: "Entrerríos" },
  { department: "Antioquia", name: "Envigado" },
  { department: "Antioquia", name: "Fredonia" },
  { department: "Antioquia", name: "Frontino" },
  { department: "Antioquia", name: "Giraldo" },
  { department: "Antioquia", name: "Girardota" },
  { department: "Antioquia", name: "Granada" },
  { department: "Antioquia", name: "Guadalupe" },
  { department: "Antioquia", name: "Guarne" },
  { department: "Antioquia", name: "Guatapé" },
  { department: "Antioquia", name: "Gómez Plata" },
  { department: "Antioquia", name: "Heliconia" },
  { department: "Antioquia", name: "Hispania" },
  { department: "Antioquia", name: "Itagüí" },
  { department: "Antioquia", name: "Ituango" },
  { department: "Antioquia", name: "Jardín" },
  { department: "Antioquia", name: "Jericó" },
  { department: "Antioquia", name: "La Ceja" },
  { department: "Antioquia", name: "La Estrella" },
  { department: "Antioquia", name: "La Pintada" },
  { department: "Antioquia", name: "La Unión" },
  { department: "Antioquia", name: "Liborina" },
  { department: "Antioquia", name: "Maceo" },
  { department: "Antioquia", name: "Marinilla" },
  { department: "Antioquia", name: "Medellín" },
  { department: "Antioquia", name: "Montebello" },
  { department: "Antioquia", name: "Murindó" },
  { department: "Antioquia", name: "Mutatá" },
  { department: "Antioquia", name: "Nariño" },
  { department: "Antioquia", name: "Nechí" },
  { department: "Antioquia", name: "Necoclí" },
  { department: "Antioquia", name: "Olaya" },
  { department: "Antioquia", name: "Peque" },
  { department: "Antioquia", name: "Pueblorrico" },
  { department: "Antioquia", name: "Puerto Berrío" },
  { department: "Antioquia", name: "Puerto Nare" },
  { department: "Antioquia", name: "Puerto Triunfo" },
  { department: "Antioquia", name: "Remedios" },
  { department: "Antioquia", name: "Rionegro" },
  { department: "Antioquia", name: "Sabanalarga" },
  { department: "Antioquia", name: "Sabaneta" },
  { department: "Antioquia", name: "Salgar" },
  { department: "Antioquia", name: "San Carlos" },
  { department: "Antioquia", name: "Segovia" },
  { department: "Antioquia", name: "Turbo" },
  { department: "Antioquia", name: "Yondó" },
  { department: "Arauca", name: "Arauca" },
  { department: "Arauca", name: "Arauquita" },
  { department: "Arauca", name: "Cravo Norte" },
  { department: "Arauca", name: "Fortul" },
  { department: "Arauca", name: "Puerto Rondón" },
  { department: "Atlántico", name: "Baranoa" },
  { department: "Atlántico", name: "Barranquilla" },
  { department: "Atlántico", name: "Campo de la Cruz" },
  { department: "Atlántico", name: "Candelaria" },
  { department: "Atlántico", name: "Galapa" },
  { department: "Atlántico", name: "Juan de Acosta" },
  { department: "Atlántico", name: "Luruaco" },
  { department: "Atlántico", name: "Malambo" },
  { department: "Atlántico", name: "Manatí" },
  { department: "Atlántico", name: "Palmar de Varela" },
  { department: "Atlántico", name: "Piojo" },
  { department: "Atlántico", name: "Piojó" },
  { department: "Atlántico", name: "Polonuevo" },
  { department: "Atlántico", name: "Ponedera" },
  { department: "Atlántico", name: "Puerto Colombia" },
  { department: "Atlántico", name: "Puerto Giraldo" },
  { department: "Atlántico", name: "Repelón" },
  { department: "Atlántico", name: "Sabanagrande" },
  { department: "Atlántico", name: "Sabanalarga" },
  { department: "Atlántico", name: "Santo Tomás" },
  { department: "Atlántico", name: "Soledad" },
  { department: "Atlántico", name: "Suán" },
  { department: "Atlántico", name: "Tubará" },
  { department: "Atlántico", name: "Usiacurí" },
  { department: "Bogotá D.C.", name: "Bogotá" },
  { department: "Bolívar", name: "Achí" },
  { department: "Bolívar", name: "Altos del Rosario" },
  { department: "Bolívar", name: "Arenal" },
  { department: "Bolívar", name: "Arjona" },
  { department: "Bolívar", name: "Arroyohondo" },
  { department: "Bolívar", name: "Barranco de Loba" },
  { department: "Bolívar", name: "Calamar" },
  { department: "Bolívar", name: "Cantagallo" },
  { department: "Bolívar", name: "Cartagena" },
  { department: "Bolívar", name: "Cartagena de Indias" },
  { department: "Bolívar", name: "Cicuco" },
  { department: "Bolívar", name: "Clemencia" },
  { department: "Bolívar", name: "Córdoba" },
  { department: "Bolívar", name: "El Carmen de Bolívar" },
  { department: "Bolívar", name: "El Guamo" },
  { department: "Bolívar", name: "El Peñón" },
  { department: "Bolívar", name: "Hatillo de Loba" },
  { department: "Bolívar", name: "Magangué" },
  { department: "Bolívar", name: "Mahates" },
  { department: "Bolívar", name: "Margarita" },
  { department: "Bolívar", name: "María La Baja" },
  { department: "Bolívar", name: "Mompós" },
  { department: "Bolívar", name: "Montecristo" },
  { department: "Bolívar", name: "Morales" },
  { department: "Bolívar", name: "Norosí" },
  { department: "Bolívar", name: "Pinillos" },
  { department: "Bolívar", name: "Regidor" },
  { department: "Bolívar", name: "Río Viejo" },
  { department: "Bolívar", name: "San Pablo" },
  { department: "Bolívar", name: "Santa Catalina" },
  { department: "Bolívar", name: "Santa Rosa del Sur" },
  { department: "Bolívar", name: "Simití" },
  { department: "Bolívar", name: "Talaigua Nuevo" },
  { department: "Bolívar", name: "Tiquisio" },
  { department: "Bolívar", name: "Turbaco" },
  { department: "Bolívar", name: "Villanueva" },
  { department: "Bolívar", name: "Zambrano" },
  { department: "Boyacá", name: "Almeida" },
  { department: "Boyacá", name: "Aquitania" },
  { department: "Boyacá", name: "Arcabuco" },
  { department: "Boyacá", name: "Belén" },
  { department: "Boyacá", name: "Berbeo" },
  { department: "Boyacá", name: "Betéitiva" },
  { department: "Boyacá", name: "Boavita" },
  { department: "Boyacá", name: "Boyacá" },
  { department: "Boyacá", name: "Briceño" },
  { department: "Boyacá", name: "Buenavista" },
  { department: "Boyacá", name: "Busbanzá" },
  { department: "Boyacá", name: "Caldas" },
  { department: "Boyacá", name: "Campohermoso" },
  { department: "Boyacá", name: "Cerinza" },
  { department: "Boyacá", name: "Chinavita" },
  { department: "Boyacá", name: "Chiquinquirá" },
  { department: "Boyacá", name: "Chiscas" },
  { department: "Boyacá", name: "Chita" },
  { department: "Boyacá", name: "Chitaraque" },
  { department: "Boyacá", name: "Chivatá" },
  { department: "Boyacá", name: "Chivor" },
  { department: "Boyacá", name: "Chíquiza" },
  { department: "Boyacá", name: "Ciénega" },
  { department: "Boyacá", name: "Coper" },
  { department: "Boyacá", name: "Corrales" },
  { department: "Boyacá", name: "Covarachía" },
  { department: "Boyacá", name: "Cubará" },
  { department: "Boyacá", name: "Cucaita" },
  { department: "Boyacá", name: "Cuítiva" },
  { department: "Boyacá", name: "Cómbita" },
  { department: "Boyacá", name: "Duitama" },
  { department: "Boyacá", name: "El Cocuy" },
  { department: "Boyacá", name: "El Espino" },
  { department: "Boyacá", name: "Firavitoba" },
  { department: "Boyacá", name: "Floresta" },
  { department: "Boyacá", name: "Gachantivá" },
  { department: "Boyacá", name: "Garagoa" },
  { department: "Boyacá", name: "Guacamayas" },
  { department: "Boyacá", name: "Guateque" },
  { department: "Boyacá", name: "Guayatá" },
  { department: "Boyacá", name: "Gámeza" },
  { department: "Boyacá", name: "Güicán" },
  { department: "Boyacá", name: "Iza" },
  { department: "Boyacá", name: "Jenesano" },
  { department: "Boyacá", name: "Jericó" },
  { department: "Boyacá", name: "La Capilla" },
  { department: "Boyacá", name: "La Uvita" },
  { department: "Boyacá", name: "La Victoria" },
  { department: "Boyacá", name: "Labranzagrande" },
  { department: "Boyacá", name: "Macanal" },
  { department: "Boyacá", name: "Maripí" },
  { department: "Boyacá", name: "Miraflores" },
  { department: "Boyacá", name: "Mongua" },
  { department: "Boyacá", name: "Monguí" },
  { department: "Boyacá", name: "Moniquirá" },
  { department: "Boyacá", name: "Motavita" },
  { department: "Boyacá", name: "Muzo" },
  { department: "Boyacá", name: "Nobsa" },
  { department: "Boyacá", name: "Nuevo Colón" },
  { department: "Boyacá", name: "Oicatá" },
  { department: "Boyacá", name: "Otanche" },
  { department: "Boyacá", name: "Pachavita" },
  { department: "Boyacá", name: "Paipa" },
  { department: "Boyacá", name: "Pajarito" },
  { department: "Boyacá", name: "Panqueba" },
  { department: "Boyacá", name: "Pauna" },
  { department: "Boyacá", name: "Paya" },
  { department: "Boyacá", name: "Paz del Río" },
  { department: "Boyacá", name: "Pesca" },
  { department: "Boyacá", name: "Pisba" },
  { department: "Boyacá", name: "Puerto Boyacá" },
  { department: "Boyacá", name: "Páez" },
  { department: "Boyacá", name: "Quípama" },
  { department: "Boyacá", name: "Ramiriquí" },
  { department: "Boyacá", name: "Rondón" },
  { department: "Boyacá", name: "Ráquira" },
  { department: "Boyacá", name: "Saboyá" },
  { department: "Boyacá", name: "Samacá" },
  { department: "Boyacá", name: "Santa Rosa de Viterbo" },
  { department: "Boyacá", name: "Sogamoso" },
  { department: "Boyacá", name: "Sora" },
  { department: "Boyacá", name: "Soracá" },
  { department: "Boyacá", name: "Sotaquirá" },
  { department: "Boyacá", name: "Sutamarchán" },
  { department: "Boyacá", name: "Sáchica" },
  { department: "Boyacá", name: "Tibasosa" },
  { department: "Boyacá", name: "Tinjacá" },
  { department: "Boyacá", name: "Tunja" },
  { department: "Boyacá", name: "Tuta" },
  { department: "Boyacá", name: "Villa de Leyva" },
  { department: "Caldas", name: "Aguadas" },
  { department: "Caldas", name: "Anserma" },
  { department: "Caldas", name: "Aranzazu" },
  { department: "Caldas", name: "Belalcázar" },
  { department: "Caldas", name: "Chinchiná" },
  { department: "Caldas", name: "Filadelfia" },
  { department: "Caldas", name: "La Dorada" },
  { department: "Caldas", name: "La Merced" },
  { department: "Caldas", name: "Manizales" },
  { department: "Caldas", name: "Manzanares" },
  { department: "Caldas", name: "Marmato" },
  { department: "Caldas", name: "Marquetalia" },
  { department: "Caldas", name: "Marulanda" },
  { department: "Caldas", name: "Neira" },
  { department: "Caldas", name: "Norcasia" },
  { department: "Caldas", name: "Palestina" },
  { department: "Caldas", name: "Pensilvania" },
  { department: "Caldas", name: "Pácora" },
  { department: "Caldas", name: "Riosucio" },
  { department: "Caldas", name: "Risaralda" },
  { department: "Caldas", name: "Salamina" },
  { department: "Caldas", name: "Samaná" },
  { department: "Caldas", name: "Supía" },
  { department: "Caldas", name: "Villamaría" },
  { department: "Caldas", name: "Viterbo" },
  { department: "Caquetá", name: "Albania" },
  { department: "Caquetá", name: "Belén de los Andaquíes" },
  { department: "Caquetá", name: "Cartagena del Chairá" },
  { department: "Caquetá", name: "Curillo" },
  { department: "Caquetá", name: "El Doncello" },
  { department: "Caquetá", name: "El Paujil" },
  { department: "Caquetá", name: "Florencia" },
  { department: "Caquetá", name: "La Montañita" },
  { department: "Caquetá", name: "Milán" },
  { department: "Caquetá", name: "Morelia" },
  { department: "Caquetá", name: "Puerto Rico" },
  { department: "Casanare", name: "Aguazul" },
  { department: "Casanare", name: "Chámeza" },
  { department: "Casanare", name: "Hato Corozal" },
  { department: "Casanare", name: "La Salina" },
  { department: "Casanare", name: "Maní" },
  { department: "Casanare", name: "Monterrey" },
  { department: "Casanare", name: "Nunchía" },
  { department: "Casanare", name: "Orocué" },
  { department: "Casanare", name: "Paz de Ariporo" },
  { department: "Casanare", name: "Pore" },
  { department: "Casanare", name: "Recetor" },
  { department: "Casanare", name: "Sabanalarga" },
  { department: "Casanare", name: "Sácama" },
  { department: "Casanare", name: "Tauramena" },
  { department: "Casanare", name: "Villanueva" },
  { department: "Casanare", name: "Yopal" },
  { department: "Cauca", name: "Almaguer" },
  { department: "Cauca", name: "Argelia" },
  { department: "Cauca", name: "Balboa" },
  { department: "Cauca", name: "Bolívar" },
  { department: "Cauca", name: "Buenos Aires" },
  { department: "Cauca", name: "Cajibío" },
  { department: "Cauca", name: "Caldono" },
  { department: "Cauca", name: "Caloto" },
  { department: "Cauca", name: "Corinto" },
  { department: "Cauca", name: "El Tambo" },
  { department: "Cauca", name: "Florencia" },
  { department: "Cauca", name: "Guachené" },
  { department: "Cauca", name: "Guapí" },
  { department: "Cauca", name: "Inzá" },
  { department: "Cauca", name: "Jambaló" },
  { department: "Cauca", name: "La Sierra" },
  { department: "Cauca", name: "La Vega" },
  { department: "Cauca", name: "López de Micay" },
  { department: "Cauca", name: "Mercaderes" },
  { department: "Cauca", name: "Miranda" },
  { department: "Cauca", name: "Morales" },
  { department: "Cauca", name: "Padilla" },
  { department: "Cauca", name: "Patía" },
  { department: "Cauca", name: "Piamonte" },
  { department: "Cauca", name: "Piendamó" },
  { department: "Cauca", name: "Popayán" },
  { department: "Cauca", name: "Puerto Tejada" },
  { department: "Cauca", name: "Puracé" },
  { department: "Cauca", name: "Páez" },
  { department: "Cauca", name: "Rosas" },
  { department: "Cauca", name: "Santander de Quilichao" },
  { department: "Cesar", name: "Aguachica" },
  { department: "Cesar", name: "Agustín Codazzi" },
  { department: "Cesar", name: "Astrea" },
  { department: "Cesar", name: "Becerril" },
  { department: "Cesar", name: "Bosconia" },
  { department: "Cesar", name: "Chimichagua" },
  { department: "Cesar", name: "Chiriguaná" },
  { department: "Cesar", name: "Curumaní" },
  { department: "Cesar", name: "El Copey" },
  { department: "Cesar", name: "El Paso" },
  { department: "Cesar", name: "Gamarra" },
  { department: "Cesar", name: "González" },
  { department: "Cesar", name: "La Gloria" },
  { department: "Cesar", name: "La Jagua de Ibirico" },
  { department: "Cesar", name: "La Paz" },
  { department: "Cesar", name: "Manaure Balcón del Cesar" },
  { department: "Cesar", name: "Pailitas" },
  { department: "Cesar", name: "Pelaya" },
  { department: "Cesar", name: "Pueblo Bello" },
  { department: "Cesar", name: "Río de Oro" },
  { department: "Cesar", name: "San Alberto" },
  { department: "Cesar", name: "San Diego" },
  { department: "Cesar", name: "Tamalameque" },
  { department: "Cesar", name: "Valledupar" },
  { department: "Chocó", name: "Acandí" },
  { department: "Chocó", name: "Alto Baudó" },
  { department: "Chocó", name: "Bagadó" },
  { department: "Chocó", name: "Bahía Solano" },
  { department: "Chocó", name: "Bajo Baudó" },
  { department: "Chocó", name: "Belén de Bajirá" },
  { department: "Chocó", name: "Bojayá" },
  { department: "Chocó", name: "Cantón de San Pablo" },
  { department: "Chocó", name: "Condoto" },
  { department: "Chocó", name: "Cértegui" },
  { department: "Chocó", name: "El Atrato" },
  { department: "Chocó", name: "El Carmen de Atrato" },
  { department: "Chocó", name: "El Carmen del Darién" },
  { department: "Chocó", name: "Istmina" },
  { department: "Chocó", name: "Juradó" },
  { department: "Chocó", name: "Litoral de San Juan" },
  { department: "Chocó", name: "Lloró" },
  { department: "Chocó", name: "Medio Atrato" },
  { department: "Chocó", name: "Medio Baudó" },
  { department: "Chocó", name: "Medio San Juan" },
  { department: "Chocó", name: "Nuquí" },
  { department: "Chocó", name: "Nóvita" },
  { department: "Chocó", name: "Quibdó" },
  { department: "Chocó", name: "Riosucio" },
  { department: "Chocó", name: "Río Iró" },
  { department: "Chocó", name: "Río Quito" },
  { department: "Cundinamarca", name: "Agua de Dios" },
  { department: "Cundinamarca", name: "Albán" },
  { department: "Cundinamarca", name: "Anapoima" },
  { department: "Cundinamarca", name: "Anolaima" },
  { department: "Cundinamarca", name: "Apulo" },
  { department: "Cundinamarca", name: "Arbeláez" },
  { department: "Cundinamarca", name: "Beltrán" },
  { department: "Cundinamarca", name: "Bituima" },
  { department: "Cundinamarca", name: "Bojacá" },
  { department: "Cundinamarca", name: "Briceño" },
  { department: "Cundinamarca", name: "Cabrera" },
  { department: "Cundinamarca", name: "Cachipay" },
  { department: "Cundinamarca", name: "Cajicá" },
  { department: "Cundinamarca", name: "Caparrapí" },
  { department: "Cundinamarca", name: "Carmen de Carupa" },
  { department: "Cundinamarca", name: "Chaguaní" },
  { department: "Cundinamarca", name: "Chipaque" },
  { department: "Cundinamarca", name: "Choachí" },
  { department: "Cundinamarca", name: "Chocontá" },
  { department: "Cundinamarca", name: "Chía" },
  { department: "Cundinamarca", name: "Cogua" },
  { department: "Cundinamarca", name: "Cota" },
  { department: "Cundinamarca", name: "Cucunubá" },
  { department: "Cundinamarca", name: "Cáqueza" },
  { department: "Cundinamarca", name: "El Colegio" },
  { department: "Cundinamarca", name: "El Peñón" },
  { department: "Cundinamarca", name: "El Rosal" },
  { department: "Cundinamarca", name: "Facatativá" },
  { department: "Cundinamarca", name: "Fosca" },
  { department: "Cundinamarca", name: "Funza" },
  { department: "Cundinamarca", name: "Fusagasugá" },
  { department: "Cundinamarca", name: "Fómeque" },
  { department: "Cundinamarca", name: "Fúquene" },
  { department: "Cundinamarca", name: "Gachalá" },
  { department: "Cundinamarca", name: "Gachancipá" },
  { department: "Cundinamarca", name: "Gachetá" },
  { department: "Cundinamarca", name: "Gama" },
  { department: "Cundinamarca", name: "Girardot" },
  { department: "Cundinamarca", name: "Granada" },
  { department: "Cundinamarca", name: "Guachetá" },
  { department: "Cundinamarca", name: "Guaduas" },
  { department: "Cundinamarca", name: "Guasca" },
  { department: "Cundinamarca", name: "Guataquí" },
  { department: "Cundinamarca", name: "Guatavita" },
  { department: "Cundinamarca", name: "Guayabal de Síquima" },
  { department: "Cundinamarca", name: "Guayabetal" },
  { department: "Cundinamarca", name: "Gutiérrez" },
  { department: "Cundinamarca", name: "Jerusalén" },
  { department: "Cundinamarca", name: "Junín" },
  { department: "Cundinamarca", name: "La Calera" },
  { department: "Cundinamarca", name: "La Mesa" },
  { department: "Cundinamarca", name: "La Palma" },
  { department: "Cundinamarca", name: "La Peña" },
  { department: "Cundinamarca", name: "La Vega" },
  { department: "Cundinamarca", name: "Lenguazaque" },
  { department: "Cundinamarca", name: "Machetá" },
  { department: "Cundinamarca", name: "Madrid" },
  { department: "Cundinamarca", name: "Manta" },
  { department: "Cundinamarca", name: "Medina" },
  { department: "Cundinamarca", name: "Mosquera" },
  { department: "Cundinamarca", name: "Nariño" },
  { department: "Cundinamarca", name: "Nemocón" },
  { department: "Cundinamarca", name: "Nilo" },
  { department: "Cundinamarca", name: "Nimaima" },
  { department: "Cundinamarca", name: "Nocaima" },
  { department: "Cundinamarca", name: "Pacho" },
  { department: "Cundinamarca", name: "Paime" },
  { department: "Cundinamarca", name: "Pandi" },
  { department: "Cundinamarca", name: "Paratebueno" },
  { department: "Cundinamarca", name: "Pasca" },
  { department: "Cundinamarca", name: "Puerto Salgar" },
  { department: "Cundinamarca", name: "Pulí" },
  { department: "Cundinamarca", name: "Quebradanegra" },
  { department: "Cundinamarca", name: "Quetame" },
  { department: "Cundinamarca", name: "Quipile" },
  { department: "Cundinamarca", name: "Ricaurte" },
  { department: "Cundinamarca", name: "Sibaté" },
  { department: "Cundinamarca", name: "Simijaca" },
  { department: "Cundinamarca", name: "Soacha" },
  { department: "Cundinamarca", name: "Sopó" },
  { department: "Cundinamarca", name: "Subachoque" },
  { department: "Cundinamarca", name: "Tabio" },
  { department: "Cundinamarca", name: "Tenjo" },
  { department: "Cundinamarca", name: "Tocancipá" },
  { department: "Cundinamarca", name: "Ubaté" },
  { department: "Cundinamarca", name: "Villapinzón" },
  { department: "Cundinamarca", name: "Villeta" },
  { department: "Cundinamarca", name: "Zipaquirá" },
  { department: "Córdoba", name: "Ayapel" },
  { department: "Córdoba", name: "Buenavista" },
  { department: "Córdoba", name: "Canalete" },
  { department: "Córdoba", name: "Cereté" },
  { department: "Córdoba", name: "Chimá" },
  { department: "Córdoba", name: "Chinú" },
  { department: "Córdoba", name: "Ciénaga de Oro" },
  { department: "Córdoba", name: "Cotorra" },
  { department: "Córdoba", name: "La Apartada" },
  { department: "Córdoba", name: "Lorica" },
  { department: "Córdoba", name: "Los Córdobas" },
  { department: "Córdoba", name: "Momil" },
  { department: "Córdoba", name: "Montelíbano" },
  { department: "Córdoba", name: "Montería" },
  { department: "Córdoba", name: "Moñitos" },
  { department: "Córdoba", name: "Planeta Rica" },
  { department: "Córdoba", name: "Pueblo Nuevo" },
  { department: "Córdoba", name: "Puerto Escondido" },
  { department: "Córdoba", name: "Puerto Libertador" },
  { department: "Córdoba", name: "Purísima" },
  { department: "Córdoba", name: "Sahagún" },
  { department: "Córdoba", name: "San Antero" },
  { department: "Córdoba", name: "San José de Uré" },
  { department: "Córdoba", name: "San Pelayo" },
  { department: "Córdoba", name: "Tierra Alta" },
  { department: "Córdoba", name: "Valencia" },
  { department: "Guainía", name: "Barrancominas" },
  { department: "Guainía", name: "Inírida" },
  { department: "Guaviare", name: "Calamar" },
  { department: "Guaviare", name: "El Retorno" },
  { department: "Guaviare", name: "Miraflores" },
  { department: "Guaviare", name: "San José del Guaviare" },
  { department: "Huila", name: "Acevedo" },
  { department: "Huila", name: "Agrado" },
  { department: "Huila", name: "Aipe" },
  { department: "Huila", name: "Algeciras" },
  { department: "Huila", name: "Altamira" },
  { department: "Huila", name: "Baraya" },
  { department: "Huila", name: "Campoalegre" },
  { department: "Huila", name: "Colombia" },
  { department: "Huila", name: "El Pital" },
  { department: "Huila", name: "Elías" },
  { department: "Huila", name: "Garzón" },
  { department: "Huila", name: "Gigante" },
  { department: "Huila", name: "Guadalupe" },
  { department: "Huila", name: "Hobo" },
  { department: "Huila", name: "Isnos" },
  { department: "Huila", name: "La Argentina" },
  { department: "Huila", name: "La Plata" },
  { department: "Huila", name: "Neiva" },
  { department: "Huila", name: "Nátaga" },
  { department: "Huila", name: "Oporapa" },
  { department: "Huila", name: "Paicol" },
  { department: "Huila", name: "Palermo" },
  { department: "Huila", name: "Palestina" },
  { department: "Huila", name: "Pitalito" },
  { department: "Huila", name: "Rivera" },
  { department: "Huila", name: "Saladoblanco" },
  { department: "Huila", name: "San Agustín" },
  { department: "Huila", name: "Timaná" },
  { department: "Huila", name: "Íquira" },
  { department: "La Guajira", name: "Albania" },
  { department: "La Guajira", name: "Barrancas" },
  { department: "La Guajira", name: "Dibulla" },
  { department: "La Guajira", name: "Distracción" },
  { department: "La Guajira", name: "El Molino" },
  { department: "La Guajira", name: "Fonseca" },
  { department: "La Guajira", name: "Hatonuevo" },
  { department: "La Guajira", name: "La Jagua del Pilar" },
  { department: "La Guajira", name: "Maicao" },
  { department: "La Guajira", name: "Manaure" },
  { department: "La Guajira", name: "Riohacha" },
  { department: "La Guajira", name: "San Juan del Cesar" },
  { department: "La Guajira", name: "Uribia" },
  { department: "La Guajira", name: "Villanueva" },
  { department: "Magdalena", name: "Algarrobo" },
  { department: "Magdalena", name: "Aracataca" },
  { department: "Magdalena", name: "Ariguaní" },
  { department: "Magdalena", name: "Cerro de San Antonio" },
  { department: "Magdalena", name: "Chibolo" },
  { department: "Magdalena", name: "Ciénaga" },
  { department: "Magdalena", name: "Concordia" },
  { department: "Magdalena", name: "El Banco" },
  { department: "Magdalena", name: "El Piñón" },
  { department: "Magdalena", name: "El Retén" },
  { department: "Magdalena", name: "Fundación" },
  { department: "Magdalena", name: "Guamal" },
  { department: "Magdalena", name: "Nueva Granada" },
  { department: "Magdalena", name: "Pedraza" },
  { department: "Magdalena", name: "Pijiño del Carmen" },
  { department: "Magdalena", name: "Pivijay" },
  { department: "Magdalena", name: "Plato" },
  { department: "Magdalena", name: "Pueblo Viejo" },
  { department: "Magdalena", name: "Remolino" },
  { department: "Magdalena", name: "Sabanas de San Ángel" },
  { department: "Magdalena", name: "Salamina" },
  { department: "Magdalena", name: "San Sebastián de Buenavista" },
  { department: "Magdalena", name: "Santa Ana" },
  { department: "Magdalena", name: "Santa Marta" },
  { department: "Magdalena", name: "Tenerife" },
  { department: "Meta", name: "Acacías" },
  { department: "Meta", name: "Barranca de Upía" },
  { department: "Meta", name: "Cabuyaro" },
  { department: "Meta", name: "Castilla la Nueva" },
  { department: "Meta", name: "Cubarral" },
  { department: "Meta", name: "Cumaral" },
  { department: "Meta", name: "El Calvario" },
  { department: "Meta", name: "El Castillo" },
  { department: "Meta", name: "El Dorado" },
  { department: "Meta", name: "Fuente de Oro" },
  { department: "Meta", name: "Granada" },
  { department: "Meta", name: "Guamal" },
  { department: "Meta", name: "La Macarena" },
  { department: "Meta", name: "La Uribe" },
  { department: "Meta", name: "Lejanías" },
  { department: "Meta", name: "Mapiripán" },
  { department: "Meta", name: "Mesetas" },
  { department: "Meta", name: "Puerto Concordia" },
  { department: "Meta", name: "Puerto Gaitán" },
  { department: "Meta", name: "Puerto Lleras" },
  { department: "Meta", name: "Puerto López" },
  { department: "Meta", name: "Puerto Rico" },
  { department: "Meta", name: "Restrepo" },
  { department: "Meta", name: "San Juan de Arama" },
  { department: "Meta", name: "San Martín" },
  { department: "Meta", name: "Uribe" },
  { department: "Meta", name: "Villavicencio" },
  { department: "Meta", name: "Vista Hermosa" },
  { department: "Nariño", name: "Aldana" },
  { department: "Nariño", name: "Ancuya" },
  { department: "Nariño", name: "Arboleda" },
  { department: "Nariño", name: "Barbacoas" },
  { department: "Nariño", name: "Belén" },
  { department: "Nariño", name: "Buesaco" },
  { department: "Nariño", name: "Chachagüí" },
  { department: "Nariño", name: "Colón" },
  { department: "Nariño", name: "Colón (Génova)" },
  { department: "Nariño", name: "Consacá" },
  { department: "Nariño", name: "Contadero" },
  { department: "Nariño", name: "Cuaspud" },
  { department: "Nariño", name: "Cumbal" },
  { department: "Nariño", name: "Cumbitara" },
  { department: "Nariño", name: "Córdoba" },
  { department: "Nariño", name: "El Charco" },
  { department: "Nariño", name: "El Peñol" },
  { department: "Nariño", name: "El Rosario" },
  { department: "Nariño", name: "El Tablón" },
  { department: "Nariño", name: "El Tablón de Gómez" },
  { department: "Nariño", name: "El Tambo" },
  { department: "Nariño", name: "Francisco Pizarro" },
  { department: "Nariño", name: "Funes" },
  { department: "Nariño", name: "Guachucal" },
  { department: "Nariño", name: "Guaitarilla" },
  { department: "Nariño", name: "Gualmatán" },
  { department: "Nariño", name: "Iles" },
  { department: "Nariño", name: "Imués" },
  { department: "Nariño", name: "Ipiales" },
  { department: "Nariño", name: "La Cruz" },
  { department: "Nariño", name: "La Florida" },
  { department: "Nariño", name: "La Llanada" },
  { department: "Nariño", name: "La Tola" },
  { department: "Nariño", name: "La Unión" },
  { department: "Nariño", name: "Leiva" },
  { department: "Nariño", name: "Linares" },
  { department: "Nariño", name: "Los Andes" },
  { department: "Nariño", name: "Magüí Payán" },
  { department: "Nariño", name: "Mallama" },
  { department: "Nariño", name: "Mosquera" },
  { department: "Nariño", name: "Nariño" },
  { department: "Nariño", name: "Olaya Herrera" },
  { department: "Nariño", name: "Ospina" },
  { department: "Nariño", name: "Pasto" },
  { department: "Nariño", name: "Policarpa" },
  { department: "Nariño", name: "Potosí" },
  { department: "Nariño", name: "Providencia" },
  { department: "Nariño", name: "Puerres" },
  { department: "Nariño", name: "Pupiales" },
  { department: "Nariño", name: "Ricaurte" },
  { department: "Nariño", name: "Roberto Payán" },
  { department: "Nariño", name: "Samaniego" },
  { department: "Nariño", name: "San Pedro de Cartago" },
  { department: "Nariño", name: "Sandoná" },
  { department: "Nariño", name: "Taminango" },
  { department: "Nariño", name: "Tangua" },
  { department: "Nariño", name: "Tumaco" },
  { department: "Nariño", name: "Túquerres" },
  { department: "Norte de Santander", name: "Arboledas" },
  { department: "Norte de Santander", name: "Bochalema" },
  { department: "Norte de Santander", name: "Bucarasica" },
  { department: "Norte de Santander", name: "Chinácota" },
  { department: "Norte de Santander", name: "Chitagá" },
  { department: "Norte de Santander", name: "Convención" },
  { department: "Norte de Santander", name: "Cucutilla" },
  { department: "Norte de Santander", name: "Cáchira" },
  { department: "Norte de Santander", name: "Cácota" },
  { department: "Norte de Santander", name: "Cúcuta" },
  { department: "Norte de Santander", name: "Duranía" },
  { department: "Norte de Santander", name: "El Carmen" },
  { department: "Norte de Santander", name: "El Tarra" },
  { department: "Norte de Santander", name: "El Zulia" },
  { department: "Norte de Santander", name: "Gramalote" },
  { department: "Norte de Santander", name: "Hacarí" },
  { department: "Norte de Santander", name: "Herrán" },
  { department: "Norte de Santander", name: "La Esperanza" },
  { department: "Norte de Santander", name: "La Playa de Belén" },
  { department: "Norte de Santander", name: "Labateca" },
  { department: "Norte de Santander", name: "Los Patios" },
  { department: "Norte de Santander", name: "Lourdes" },
  { department: "Norte de Santander", name: "Mutiscua" },
  { department: "Norte de Santander", name: "Ocaña" },
  { department: "Norte de Santander", name: "Pamplona" },
  { department: "Norte de Santander", name: "Pamplonita" },
  { department: "Norte de Santander", name: "Puerto Santander" },
  { department: "Norte de Santander", name: "Ragonvalia" },
  { department: "Norte de Santander", name: "Salazar de Las Palmas" },
  { department: "Norte de Santander", name: "San Calixto" },
  { department: "Norte de Santander", name: "Teorama" },
  { department: "Norte de Santander", name: "Villa del Rosario" },
  { department: "Norte de Santander", name: "Ábrego" },
  { department: "Putumayo", name: "Colón" },
  { department: "Putumayo", name: "Mocoa" },
  { department: "Putumayo", name: "Orito" },
  { department: "Putumayo", name: "Puerto Asís" },
  { department: "Putumayo", name: "Puerto Caicedo" },
  { department: "Putumayo", name: "Puerto Guzmán" },
  { department: "Putumayo", name: "Puerto Leguízamo" },
  { department: "Putumayo", name: "San Francisco" },
  { department: "Putumayo", name: "San Miguel" },
  { department: "Putumayo", name: "Santiago" },
  { department: "Putumayo", name: "Sibundoy" },
  { department: "Putumayo", name: "Valle del Guamez" },
  { department: "Putumayo", name: "Villa Garzón" },
  { department: "Quindío", name: "Armenia" },
  { department: "Quindío", name: "Buenavista" },
  { department: "Quindío", name: "Calarcá" },
  { department: "Quindío", name: "Circasia" },
  { department: "Quindío", name: "Córdoba" },
  { department: "Quindío", name: "Filandia" },
  { department: "Quindío", name: "Génova" },
  { department: "Quindío", name: "La Tebaida" },
  { department: "Quindío", name: "Montenegro" },
  { department: "Quindío", name: "Pijao" },
  { department: "Quindío", name: "Quimbaya" },
  { department: "Quindío", name: "Salento" },
  { department: "Risaralda", name: "Apía" },
  { department: "Risaralda", name: "Balboa" },
  { department: "Risaralda", name: "Belén de Umbría" },
  { department: "Risaralda", name: "Dosquebradas" },
  { department: "Risaralda", name: "Guática" },
  { department: "Risaralda", name: "La Celia" },
  { department: "Risaralda", name: "La Virginia" },
  { department: "Risaralda", name: "Marsella" },
  { department: "Risaralda", name: "Mistrató" },
  { department: "Risaralda", name: "Pereira" },
  { department: "Risaralda", name: "Pueblo Rico" },
  { department: "Risaralda", name: "Quinchía" },
  { department: "Risaralda", name: "Santa Rosa de Cabal" },
  { department: "San Andrés y Providencia", name: "Providencia y Santa Catalina Islas" },
  { department: "San Andrés y Providencia", name: "San Andrés" },
  { department: "Santander", name: "Aguada" },
  { department: "Santander", name: "Albania" },
  { department: "Santander", name: "Aratoca" },
  { department: "Santander", name: "Barbosa" },
  { department: "Santander", name: "Barichara" },
  { department: "Santander", name: "Barrancabermeja" },
  { department: "Santander", name: "Betulia" },
  { department: "Santander", name: "Bolívar" },
  { department: "Santander", name: "Bucaramanga" },
  { department: "Santander", name: "Cabrera" },
  { department: "Santander", name: "California" },
  { department: "Santander", name: "Capitanejo" },
  { department: "Santander", name: "Carcasí" },
  { department: "Santander", name: "Cepitá" },
  { department: "Santander", name: "Cerrito" },
  { department: "Santander", name: "Charalá" },
  { department: "Santander", name: "Charta" },
  { department: "Santander", name: "Chima" },
  { department: "Santander", name: "Chipatá" },
  { department: "Santander", name: "Cimitarra" },
  { department: "Santander", name: "Concepción" },
  { department: "Santander", name: "Confines" },
  { department: "Santander", name: "Contratación" },
  { department: "Santander", name: "Coromoro" },
  { department: "Santander", name: "Curití" },
  { department: "Santander", name: "El Carmen de Chucurí" },
  { department: "Santander", name: "El Guacamayo" },
  { department: "Santander", name: "El Peñón" },
  { department: "Santander", name: "El Playón" },
  { department: "Santander", name: "El Socorro" },
  { department: "Santander", name: "Encino" },
  { department: "Santander", name: "Enciso" },
  { department: "Santander", name: "Floridablanca" },
  { department: "Santander", name: "Florián" },
  { department: "Santander", name: "Galán" },
  { department: "Santander", name: "Girón" },
  { department: "Santander", name: "Guaca" },
  { department: "Santander", name: "Guadalupe" },
  { department: "Santander", name: "Guapotá" },
  { department: "Santander", name: "Guavatá" },
  { department: "Santander", name: "Gámbita" },
  { department: "Santander", name: "Güepsa" },
  { department: "Santander", name: "Hato" },
  { department: "Santander", name: "Jesús María" },
  { department: "Santander", name: "Jordán" },
  { department: "Santander", name: "La Belleza" },
  { department: "Santander", name: "La Paz" },
  { department: "Santander", name: "Landázuri" },
  { department: "Santander", name: "Lebrija" },
  { department: "Santander", name: "Los Santos" },
  { department: "Santander", name: "Macaravita" },
  { department: "Santander", name: "Matanza" },
  { department: "Santander", name: "Mogotes" },
  { department: "Santander", name: "Molagavita" },
  { department: "Santander", name: "Málaga" },
  { department: "Santander", name: "Ocamonte" },
  { department: "Santander", name: "Oiba" },
  { department: "Santander", name: "Onzaga" },
  { department: "Santander", name: "Palmar" },
  { department: "Santander", name: "Palmas del Socorro" },
  { department: "Santander", name: "Piedecuesta" },
  { department: "Santander", name: "Pinchote" },
  { department: "Santander", name: "Puente Nacional" },
  { department: "Santander", name: "Puerto Parra" },
  { department: "Santander", name: "Puerto Wilches" },
  { department: "Santander", name: "Páramo" },
  { department: "Santander", name: "Rionegro" },
  { department: "Santander", name: "Sabana de Torres" },
  { department: "Santander", name: "San Andrés" },
  { department: "Santander", name: "San Gil" },
  { department: "Santander", name: "San Joaquín" },
  { department: "Santander", name: "Villanueva" },
  { department: "Santander", name: "Vélez" },
  { department: "Sucre", name: "Buenavista" },
  { department: "Sucre", name: "Caimito" },
  { department: "Sucre", name: "Chalán" },
  { department: "Sucre", name: "Colosó" },
  { department: "Sucre", name: "Corozal" },
  { department: "Sucre", name: "Coveñas" },
  { department: "Sucre", name: "El Roble" },
  { department: "Sucre", name: "Galeras" },
  { department: "Sucre", name: "Guaranda" },
  { department: "Sucre", name: "La Unión" },
  { department: "Sucre", name: "Los Palmitos" },
  { department: "Sucre", name: "Majagual" },
  { department: "Sucre", name: "Morroa" },
  { department: "Sucre", name: "Ovejas" },
  { department: "Sucre", name: "Sampués" },
  { department: "Sucre", name: "San Pedro" },
  { department: "Sucre", name: "Sincelejo" },
  { department: "Sucre", name: "Toluviejo" },
  { department: "Sucre", name: "Tolú" },
  { department: "Tolima", name: "Alpujarra" },
  { department: "Tolima", name: "Alvarado" },
  { department: "Tolima", name: "Ambalema" },
  { department: "Tolima", name: "Anzoátegui" },
  { department: "Tolima", name: "Armero" },
  { department: "Tolima", name: "Armero-Guayabal" },
  { department: "Tolima", name: "Ataco" },
  { department: "Tolima", name: "Cajamarca" },
  { department: "Tolima", name: "Carmen de Apicalá" },
  { department: "Tolima", name: "Casabianca" },
  { department: "Tolima", name: "Chaparral" },
  { department: "Tolima", name: "Coello" },
  { department: "Tolima", name: "Coyaima" },
  { department: "Tolima", name: "Cunday" },
  { department: "Tolima", name: "Dolores" },
  { department: "Tolima", name: "El Espinal" },
  { department: "Tolima", name: "El Líbano" },
  { department: "Tolima", name: "Espinal" },
  { department: "Tolima", name: "Falan" },
  { department: "Tolima", name: "Flandes" },
  { department: "Tolima", name: "Fresno" },
  { department: "Tolima", name: "Guamo" },
  { department: "Tolima", name: "Herveo" },
  { department: "Tolima", name: "Honda" },
  { department: "Tolima", name: "Ibagué" },
  { department: "Tolima", name: "Icononzo" },
  { department: "Tolima", name: "Lérida" },
  { department: "Tolima", name: "Líbano" },
  { department: "Tolima", name: "Mariquita" },
  { department: "Tolima", name: "Melgar" },
  { department: "Tolima", name: "Murillo" },
  { department: "Tolima", name: "Natagaima" },
  { department: "Tolima", name: "Ortega" },
  { department: "Tolima", name: "Palocabildo" },
  { department: "Tolima", name: "Piedras" },
  { department: "Tolima", name: "Planadas" },
  { department: "Tolima", name: "Prado" },
  { department: "Tolima", name: "Purificación" },
  { department: "Tolima", name: "Rioblanco" },
  { department: "Tolima", name: "Roncesvalles" },
  { department: "Tolima", name: "Rovira" },
  { department: "Tolima", name: "Saldaña" },
  { department: "Tolima", name: "Venadillo" },
  { department: "Tolima", name: "Villahermosa" },
  { department: "Valle del Cauca", name: "Alcalá" },
  { department: "Valle del Cauca", name: "Andalucía" },
  { department: "Valle del Cauca", name: "Ansermanuevo" },
  { department: "Valle del Cauca", name: "Argelia" },
  { department: "Valle del Cauca", name: "Bolívar" },
  { department: "Valle del Cauca", name: "Buenaventura" },
  { department: "Valle del Cauca", name: "Buga" },
  { department: "Valle del Cauca", name: "Buga (Guadalajara de Buga)" },
  { department: "Valle del Cauca", name: "Bugalagrande" },
  { department: "Valle del Cauca", name: "Caicedonia" },
  { department: "Valle del Cauca", name: "Cali" },
  { department: "Valle del Cauca", name: "Calima" },
  { department: "Valle del Cauca", name: "Candelaria" },
  { department: "Valle del Cauca", name: "Cartago" },
  { department: "Valle del Cauca", name: "Dagua" },
  { department: "Valle del Cauca", name: "El Cairo" },
  { department: "Valle del Cauca", name: "El Cerrito" },
  { department: "Valle del Cauca", name: "El Dovio" },
  { department: "Valle del Cauca", name: "El Águila" },
  { department: "Valle del Cauca", name: "Florida" },
  { department: "Valle del Cauca", name: "Ginebra" },
  { department: "Valle del Cauca", name: "Guacarí" },
  { department: "Valle del Cauca", name: "Jamundí" },
  { department: "Valle del Cauca", name: "La Cumbre" },
  { department: "Valle del Cauca", name: "La Unión" },
  { department: "Valle del Cauca", name: "La Victoria" },
  { department: "Valle del Cauca", name: "Obando" },
  { department: "Valle del Cauca", name: "Palmira" },
  { department: "Valle del Cauca", name: "Pradera" },
  { department: "Valle del Cauca", name: "Restrepo" },
  { department: "Valle del Cauca", name: "Riofrío" },
  { department: "Valle del Cauca", name: "Roldanillo" },
  { department: "Valle del Cauca", name: "San Pedro" },
  { department: "Valle del Cauca", name: "Sevilla" },
  { department: "Valle del Cauca", name: "Toro" },
  { department: "Valle del Cauca", name: "Tuluá" },
  { department: "Valle del Cauca", name: "Ulloa" },
  { department: "Valle del Cauca", name: "Yumbo" },
  { department: "Valle del Cauca", name: "Zarzal" },
  { department: "Vaupés", name: "Carurú" },
  { department: "Vaupés", name: "Mitú" },
  { department: "Vichada", name: "Cumaribo" },
  { department: "Vichada", name: "La Primavera" },
  { department: "Vichada", name: "Puerto Carreño" },
];
